### SITE
GET http://localhost:3030/


### REGISTER
POST http://localhost:3030/api/v1/auth/register
Content-Type: application/json

{
    "name": "nguyen11",
    "email": "nguyen11@fpt.com",
    "password": "123456",
    "passwordConfirm": "123456"
}


### LOGIN
POST http://localhost:3030/api/v1/auth/login
Content-Type: application/json

{
    "email": "admin@fpt.com",
    "password": "123456"
}


### LOGOUT
DELETE http://localhost:3030/api/v1/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMDY4NzI2NSwiZXhwIjoxNzIwNjg3ODY1fQ.YZZ96aBFf2jEvOTLf66J6MtQe6YThsqBOxzUUO-O_dc"
}


### REFRESH TOKEN
POST http://localhost:3030/api/v1/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTY1Mzk0NWVjODA5ZDhhODkzNTQiLCJuYW1lIjoibmd1eWVuMSIsImVtYWlsIjoibmd1eWVuMUBmcHQuY29tIiwicm9sZSI6Ik1lbWJlciIsImlhdCI6MTcyMDY4NjgxNCwiZXhwIjoxNzIwNjg3NDE0fQ.C_QZpG-wDEdQiJz6ru8O0h1qVL7HAyK4_08LZs4f5MA"
}


### GET LIST USER BY ADMIN
GET http://localhost:3030/api/v1/user/get-user-list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMDY5MDE3NiwiZXhwIjoxNzIwNjkwNDc2fQ.qxtbiNvLFcf0k2C_EuXzd6HaynwsukuEOdioQzjwxH8


### GET LIST MEETING ROOM
GET http://localhost:3030/api/v1/meeting-room/get-meeting-room-list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMDc3MDk3NywiZXhwIjoxNzIwNzgwOTc3fQ._zfWyZF7ZKvKx78KNbVFOMgHRpXhkBy9s61je5Ev42Y


### ADD MEETING ROOM
POST http://localhost:3030/api/v1/meeting-room/save-meeting-room
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMDc1MjA3OSwiZXhwIjoxNzIwNzUzMDc5fQ.OEryOPSReP7pRm7as79RIqK8v6bDel5q91MI5HUpDeA

{
    "roomName": "Phòng Họp FIS",
    "capacity": 25,
    "location": "Đường số 1, tòa Nhà FPT",
    "status": true
}


### UPDATE STATE MEETING ROOM
PATCH http://localhost:3030/api/v1/meeting-room/update-state-meeting-room/6690d5afa00f38479095d834
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMDc3MDk3NywiZXhwIjoxNzIwNzgwOTc3fQ._zfWyZF7ZKvKx78KNbVFOMgHRpXhkBy9s61je5Ev42Y

{
    "meetingRoomStatus": true
}


### UPDATE MEETING ROOM
PUT http://localhost:3030/api/v1/meeting-room/update-meeting-room/6690d5afa00f38479095d834
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMDc3MDk3NywiZXhwIjoxNzIwNzgwOTc3fQ._zfWyZF7ZKvKx78KNbVFOMgHRpXhkBy9s61je5Ev42Y

{
    "roomName": "Phòng Họp TEST",
    "capacity": 111,
    "location": "Đường số 1, tòa Nhà FPT",
    "status": true
}


### SOFT DELETE MEETING ROOM
DELETE http://localhost:3030/api/v1/meeting-room/soft-delete-meeting-room/6690d5afa00f38479095d834
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMDc3MDk3NywiZXhwIjoxNzIwNzgwOTc3fQ._zfWyZF7ZKvKx78KNbVFOMgHRpXhkBy9s61je5Ev42Y


### GET LIST MEETING ROOM FROM TRASH
GET http://localhost:3030/api/v1/meeting-room/trash-meeting-room
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMDc3MDk3NywiZXhwIjoxNzIwNzgwOTc3fQ._zfWyZF7ZKvKx78KNbVFOMgHRpXhkBy9s61je5Ev42Y


### RESTORE MEETING ROOM
PATCH http://localhost:3030/api/v1/meeting-room/restore-meeting-room/6690d5afa00f38479095d834
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMDc3MDk3NywiZXhwIjoxNzIwNzgwOTc3fQ._zfWyZF7ZKvKx78KNbVFOMgHRpXhkBy9s61je5Ev42Y


### DESTROY MEETING ROOM
DELETE http://localhost:3030/api/v1/meeting-room/destroy-meeting-room/6690d5afa00f38479095d834
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMDc3MDk3NywiZXhwIjoxNzIwNzgwOTc3fQ._zfWyZF7ZKvKx78KNbVFOMgHRpXhkBy9s61je5Ev42Y

