### SITE
GET http://localhost:3030/


-------------------------------------------------------------------------------------------------


### REGISTER
POST http://localhost:3030/api/v1/auth/register
Content-Type: application/json

{
    "name": "nguyen11",
    "email": "nguyen11@fpt.com",
    "password": "123456",
    "passwordConfirm": "123456"
}


### LOGIN
POST http://localhost:3030/api/v1/auth/login
Content-Type: application/json

{
    "email": "admin@fpt.com",
    "password": "123456"
}


### LOGOUT
DELETE http://localhost:3030/api/v1/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMDY4NzI2NSwiZXhwIjoxNzIwNjg3ODY1fQ.YZZ96aBFf2jEvOTLf66J6MtQe6YThsqBOxzUUO-O_dc"
}


### REFRESH TOKEN
POST http://localhost:3030/api/v1/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTY1Mzk0NWVjODA5ZDhhODkzNTQiLCJuYW1lIjoibmd1eWVuMSIsImVtYWlsIjoibmd1eWVuMUBmcHQuY29tIiwicm9sZSI6Ik1lbWJlciIsImlhdCI6MTcyMDY4NjgxNCwiZXhwIjoxNzIwNjg3NDE0fQ.C_QZpG-wDEdQiJz6ru8O0h1qVL7HAyK4_08LZs4f5MA"
}


-------------------------------------------------------------------------------------------------


### GET LIST USER
GET http://localhost:3030/api/v1/user/get-user-list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMDY5MDE3NiwiZXhwIjoxNzIwNjkwNDc2fQ.qxtbiNvLFcf0k2C_EuXzd6HaynwsukuEOdioQzjwxH8


### GET USER BY ID
GET http://localhost:3030/api/v1/user/get-user/668f9609c2df07ed87613ab3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMTExMTg1OCwiZXhwIjoxNzIxMTIxODU4fQ.8JKG4Z9pm5RkV4kC2xEYea1qYCMgAPvqrFtFMaDOYMw


-------------------------------------------------------------------------------------------------


### GET LIST MEETING ROOM
GET http://localhost:3030/api/v1/meeting-room/get-meeting-room-list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMTA5NTE1NCwiZXhwIjoxNzIxMTA1MTU0fQ.R5Oh8KI-YzbDDE4S4LQzMpARzguXQN1-VP1fRfTX5Y0


### GET MEETING ROOM BY ID
GET http://localhost:3030/api/v1/meeting-room/get-meeting-room/668fb301b87bf2a9f3282779
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMTExMTg1OCwiZXhwIjoxNzIxMTIxODU4fQ.8JKG4Z9pm5RkV4kC2xEYea1qYCMgAPvqrFtFMaDOYMw


### ADD MEETING ROOM
POST http://localhost:3030/api/v1/meeting-room/save-meeting-room
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMDc1MjA3OSwiZXhwIjoxNzIwNzUzMDc5fQ.OEryOPSReP7pRm7as79RIqK8v6bDel5q91MI5HUpDeA

{
    "roomName": "Phòng Họp FIS",
    "capacity": 25,
    "location": "Đường số 1, tòa Nhà FPT",
    "status": true
}


### UPDATE STATE MEETING ROOM
PATCH http://localhost:3030/api/v1/meeting-room/update-state-meeting-room/668fb3bfb87bf2a9f328277c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMTA5NTE1NCwiZXhwIjoxNzIxMTA1MTU0fQ.R5Oh8KI-YzbDDE4S4LQzMpARzguXQN1-VP1fRfTX5Y0

{
    "meetingRoomStatus": true
}


### UPDATE MEETING ROOM
PUT http://localhost:3030/api/v1/meeting-room/update-meeting-room/6690d5afa00f38479095d834
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMTA5NTE1NCwiZXhwIjoxNzIxMTA1MTU0fQ.R5Oh8KI-YzbDDE4S4LQzMpARzguXQN1-VP1fRfTX5Y0

{
    "roomName": "Phòng Họp TEST",
    "capacity": 111,
    "location": "Đường số 1, tòa Nhà FPT",
    "status": true
}


### SOFT DELETE MEETING ROOM
DELETE http://localhost:3030/api/v1/meeting-room/soft-delete-meeting-room/668fb3bfb87bf2a9f328277c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMTA5NTE1NCwiZXhwIjoxNzIxMTA1MTU0fQ.R5Oh8KI-YzbDDE4S4LQzMpARzguXQN1-VP1fRfTX5Y0


### GET LIST MEETING ROOM FROM TRASH
GET http://localhost:3030/api/v1/meeting-room/trash-meeting-room
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMTExMTg1OCwiZXhwIjoxNzIxMTIxODU4fQ.8JKG4Z9pm5RkV4kC2xEYea1qYCMgAPvqrFtFMaDOYMw


### RESTORE MEETING ROOM
PATCH http://localhost:3030/api/v1/meeting-room/restore-meeting-room/668fb3bfb87bf2a9f328277c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMTExMTg1OCwiZXhwIjoxNzIxMTIxODU4fQ.8JKG4Z9pm5RkV4kC2xEYea1qYCMgAPvqrFtFMaDOYMw


### DESTROY MEETING ROOM
DELETE http://localhost:3030/api/v1/meeting-room/destroy-meeting-room/6690d5afa00f38479095d834
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMDc3MDk3NywiZXhwIjoxNzIwNzgwOTc3fQ._zfWyZF7ZKvKx78KNbVFOMgHRpXhkBy9s61je5Ev42Y


-------------------------------------------------------------------------------------------------

### GET LIST MEETING
GET http://localhost:3030/api/v1/meeting/get-       
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMTM1NjMyMSwiZXhwIjoxNzIxMzY2MzIxfQ.9oIjMY40j1-MrYfuIVYdHu6GnyR-wt5Cv4S8TO5qyes


### GET MEETING BY ID
GET http://localhost:3030/api/v1/meeting/get-meeting/669f8315a12bccf4f671446a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMTM1NjMyMSwiZXhwIjoxNzIxMzY2MzIxfQ.9oIjMY40j1-MrYfuIVYdHu6GnyR-wt5Cv4S8TO5qyes


### GET MEETING BY WEEK
GET http://localhost:3030/api/v1/meeting/get-meeting-list-by-week?startDate=2024-07-22T00:00:00.000Z&endDate=2024-07-28T00:00:00.000Z
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMTM1NjMyMSwiZXhwIjoxNzIxMzY2MzIxfQ.9oIjMY40j1-MrYfuIVYdHu6GnyR-wt5Cv4S8TO5qyes


### GET MEETING BY DAY
GET http://localhost:3030/api/v1/meeting/get-meeting-list-by-day?date=2024-07-26T00:00:00.000Z
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMTM1NjMyMSwiZXhwIjoxNzIxMzY2MzIxfQ.9oIjMY40j1-MrYfuIVYdHu6GnyR-wt5Cv4S8TO5qyes


### GET MEETING BY DAY
GET http://localhost:3030/api/v1/meeting/get-available-meeting-times-during-day?date=2024-07-24T00:00:00.000Z
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMTM1NjMyMSwiZXhwIjoxNzIxMzY2MzIxfQ.9oIjMY40j1-MrYfuIVYdHu6GnyR-wt5Cv4S8TO5qyes


### CREATE MEETING WITHOUT PARTICIPANTS
POST http://localhost:3030/api/v1/meeting/save-meeting
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMTA5NTE1NCwiZXhwIjoxNzIxMTA1MTU0fQ.R5Oh8KI-YzbDDE4S4LQzMpARzguXQN1-VP1fRfTX5Y0

{
    "meetingName": "meetingName",
    "description": "description",
    "department": "department",
    "startTime": "2024-07-19T07:00:00Z",
    "endTime": "2024-07-19T10:00:00Z",
    "status": "completed",
    "roomId": "668fb301b87bf2a9f3282779"
}


### CREATE MEETING WITH PARTICIPANTS
POST http://localhost:3030/api/v1/meeting/create-meeting-with-participants
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMTM3MDc3MSwiZXhwIjoxNzIxMzgwNzcxfQ.ieaXJ8sPlZOWC3bYFPuCU-w3WjRJpPqRl_xI37ZgwnU

{
    "meetingName": "meetingName",
    "description": "description",
    "department": "department",
    "startTime": "2024-07-31T10:00:00Z",
    "endTime": "2024-07-31T11:00:00Z",
    "status": "scheduled",
    "roomId": "668fb3bfb87bf2a9f328277c",
    "participantIDs": ["668f9671945ec809d8a89358", "668f9653945ec809d8a89354", "668f967b945ec809d8a8935b"]
}


### UPDATE STATE MEETING
PATCH http://localhost:3030/api/v1/meeting/update-state-meeting/6695e149c93f2a66408a67ed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMTA5NTE1NCwiZXhwIjoxNzIxMTA1MTU0fQ.R5Oh8KI-YzbDDE4S4LQzMpARzguXQN1-VP1fRfTX5Y0

{
    "status": "cancelled"
}


### UPDATE MEETING
PUT http://localhost:3030/api/v1/meeting/update-meeting/6695e149c93f2a66408a67ed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMTA5NTE1NCwiZXhwIjoxNzIxMTA1MTU0fQ.R5Oh8KI-YzbDDE4S4LQzMpARzguXQN1-VP1fRfTX5Y0

{
    "meetingName": "meetingName test",
    "description": "description test",
    "department": "department test",
    "startTime": "2024-07-19T10:00:00Z",
    "endTime": "2024-07-20T10:00:00Z",
    "status": "ongoing",
    "roomId": "669097dac08685adafcbc0bf"
}


### SOFT DELETE MEETING
DELETE http://localhost:3030/api/v1/meeting/soft-delete-meeting/6695e149c93f2a66408a67ed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMTExMTg1OCwiZXhwIjoxNzIxMTIxODU4fQ.8JKG4Z9pm5RkV4kC2xEYea1qYCMgAPvqrFtFMaDOYMw


### GET LIST MEETING FROM TRASH
GET http://localhost:3030/api/v1/meeting/trash-meeting
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMTExMTg1OCwiZXhwIjoxNzIxMTIxODU4fQ.8JKG4Z9pm5RkV4kC2xEYea1qYCMgAPvqrFtFMaDOYMw


### RESTORE MEETING
PATCH http://localhost:3030/api/v1/meeting/restore-meeting/6695e149c93f2a66408a67ed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMTA5NTE1NCwiZXhwIjoxNzIxMTA1MTU0fQ.R5Oh8KI-YzbDDE4S4LQzMpARzguXQN1-VP1fRfTX5Y0


### DESTROY MEETING ROOM
DELETE http://localhost:3030/api/v1/meeting/destroy-meeting/6695ec4831029e22bb36d679
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMTA5NTE1NCwiZXhwIjoxNzIxMTA1MTU0fQ.R5Oh8KI-YzbDDE4S4LQzMpARzguXQN1-VP1fRfTX5Y0