### SITE
GET http://localhost:3030/


### REGISTER
POST http://localhost:3030/api/v1/auth/register
Content-Type: application/json

{
    "name": "nguyen10",
    "email": "nguyen10@fpt.com",
    "password": "123456",
    "passwordConfirm": "123456"
}


### LOGIN
POST http://localhost:3030/api/v1/auth/login
Content-Type: application/json

{
    "email": "admin@fpt.com",
    "password": "123456"
}


### LOGOUT
DELETE http://localhost:3030/api/v1/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMDY4NzI2NSwiZXhwIjoxNzIwNjg3ODY1fQ.YZZ96aBFf2jEvOTLf66J6MtQe6YThsqBOxzUUO-O_dc"
}


### REFRESH TOKEN
POST http://localhost:3030/api/v1/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTY1Mzk0NWVjODA5ZDhhODkzNTQiLCJuYW1lIjoibmd1eWVuMSIsImVtYWlsIjoibmd1eWVuMUBmcHQuY29tIiwicm9sZSI6Ik1lbWJlciIsImlhdCI6MTcyMDY4NjgxNCwiZXhwIjoxNzIwNjg3NDE0fQ.C_QZpG-wDEdQiJz6ru8O0h1qVL7HAyK4_08LZs4f5MA"
}


### GET LIST USER BY ADMIN
GET http://localhost:3030/api/v1/user/get-user-list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMDY5MDE3NiwiZXhwIjoxNzIwNjkwNDc2fQ.qxtbiNvLFcf0k2C_EuXzd6HaynwsukuEOdioQzjwxH8


### GET LIST MEETING ROOM BY ADMIN
GET http://localhost:3030/api/v1/meeting-room/get-meeting-room-list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMDY5MTQyOCwiZXhwIjoxNzIwNjkxNzI4fQ.vpTOUSDrX8f4Ix8QQsh2qY_2hSA-CwOviTGc6afWRLI


### ADD MEETING ROOM
POST http://localhost:3030/api/v1/meeting-room/save-meetingRoom
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMDc1MjA3OSwiZXhwIjoxNzIwNzUzMDc5fQ.OEryOPSReP7pRm7as79RIqK8v6bDel5q91MI5HUpDeA

{
    "roomName": "Phòng Họp FIS",
    "capacity": 25,
    "location": "Đường số 1, tòa Nhà FPT",
    "status": true
}


### UPDATE STATE MEETING ROOM
PATCH http://localhost:3030/api/v1/meeting-room/update-state-meeting-room/668fb301b87bf2a9f3282779
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMDc1Mzg1MywiZXhwIjoxNzIwNzYzODUzfQ.R6-jViLRNmf2pEFh8D09NNMTX7c4hVEcqFWOMuZ-jBg

{
    "meetingRoomStatus": false
}


### UPDATE MEETING ROOM
PUT http://localhost:3030/api/v1/meeting-room/update-meeting-room/668fb301b87bf2a9f3282779
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmOTQ0YmRmZGYxNDIzYzY1OTEwNmQiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImVtYWlsIjoiYWRtaW5AZnB0LmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyMDc1Mzg1MywiZXhwIjoxNzIwNzYzODUzfQ.R6-jViLRNmf2pEFh8D09NNMTX7c4hVEcqFWOMuZ-jBg

{
    "roomName": "Phòng Họp DT",
    "capacity": 30,
    "location": "Đường số 1, tòa Nhà FPT",
    "status": false
}